# Generated by Django 4.1.7 on 2023-05-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('subsystem', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='subsystem',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.actuator')),
            ],
        ),
    ]
